---
dist: xenial

git:
  depth: false

sudo: required

addons:
  sonarcloud:
    organization: "stefanoagazzi-github"
    token:
      secure: >
        "XS+h/Iak3EewqnVR00nkxZd715eh1ghZ0gewhLYSPoWUp8DJ7xzM1cmHplCyG/Wxxj8Wzy9w
        XQKF/wSLTb5H1NIsVoVWlMoP84V/+yc5wmhtfbAbUPQ9EmsDuuhC2pEj4V0yC34JYFNv2GsnD
        5DtIol2wP+C+eeYhTvNATxVCXXwBO/oIJocq/aXY8ZvYxQoP0mg7k+rKJJCFy5qJG6Qg9ia4Y
        bh3tGrWL8lbwk5STrcYYN58hZLrWhcXEe2Jh+XiYFp0Bdwg9FPY3Qx2RDc3FVl6l5Qm+vktLG
        ZJnmH+MJXG2xaKdrCA7XBmkK/f2gterkpZ6a2x6b6Q+0vtJhYIwiGVeXvDGc98a94kvwq06cc
        47vdMywH9gjc11dRqW+O/QQBEtPM4f4GYljMcW5bRMes3AdRCYO8DY8HWPC6PfA/O9Qt4zVZ2
        b/4xs+wDt4FCRh0dvPXDe2ACZHR1oIQ7CJL4JMY3r4ep8Zf7Xj5QjgMXXEnCrNCqyjMbcGdxE
        2psui3nyD4BhW0Rlip5bUoy/GOpeW2UuZiPp46IMPG/ipphzrY0Li2dN0PSJtzCBb6yN1whBk
        rI5bi5AdUVpV6lwBbVQjcSY8Flm6eB070+SnkFDp9KtBL0fS/vKxPz5FxBfbQOo3/dQtqx5Lo
        v1C6/Un9wjZpZ9Rq5N5PyXSjDng="

language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install --assume-yes docker-ce
  - docker --version

install:
  - pip install -r requirements.txt

script:
  - ansible-lint tasks/main.yml
  - molecule test
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
