---
sudo: required
language: python
services:
- docker

before_install:
- sudo apt-get -qq update
- sudo apt-get install --option Dpkg::Options::="--force-confold" --force-yes --assume-yes docker-ce
- docker --version

install:
- pip install molecule ansible docker

script:
# check the role/playbook's syntax.
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
- ansible-lint tasks/main.yml
- ansible-review tasks/main.yml

# start test
- molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
