# tasks file for base-centos7
---
- name:                  Ensure we have last version of every package
  tags:
  - skip_ansible_lint
  package:
    name:                '*'
    state:               latest

- name:                  Ensure EPEL is present
  package:
    name:                epel-release
    state:               present

#- name:                 Ensure copr repo for dnf-centos is enabled
#  yum_repository:
#    name:               copr-dnf-centos
#    description:        Copr repo for dnf-centos owned by @rpm-software-management
#    baseurl:            https://copr-be.cloud.fedoraproject.org/results/@rpm-software-management/dnf-centos/epel-7-$basearch/
#    gpgkey:             https://copr-be.cloud.fedoraproject.org/results/@rpm-software-management/dnf-centos/pubkey.gpg
#    gpgcheck:           yes
#    repo_gpgcheck:      no
#    skip_if_unavailable: yes
#    enabled:            yes

- name:                  Ensure ELRepo GPG key is present
  rpm_key:
    state:               present
    key:                 https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name:                  Ensure ELRepo is enabled
  package:
    name:                http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
    state:               present

- name:                  Ensure copr repo for OpenSCAP is enabled
  yum_repository:
    name:                copr-openscap
    description:         OpenSCAP copr lastest
    baseurl:             https://copr-be.cloud.fedoraproject.org/results/openscapmaint/openscap-latest/epel-7-$basearch/
    gpgkey:              https://copr-be.cloud.fedoraproject.org/results/openscapmaint/openscap-latest/pubkey.gpg
    gpgcheck:            yes
    repo_gpgcheck:       no
    skip_if_unavailable: yes
    enabled:             yes

- name:                  Ensure CentOS extras repo is enabled
  command:               "{{ item }}"
  with_items:
  - yum-config-manager --enable extras arg1
  - touch CentOS-Base-extras.enabled arg1
  args:
    creates:             /CentOS-Base-extras.enabled

- name:                  Ensure we have last version of every package
  tags:
  - skip_ansible_lint
  package:
    name:                '*'
    state:               latest

- name:                  Ensure Python is present
  package:
    name:                python
    state:               present

- name:                  Ensure libselinux-python is present
  package:
    name:                libselinux-python
    state:               present

- name:                  Ensure libsemanage-python is present
  package:
    name:                libsemanage-python
    state:               present

- name:                  Ensure NTP is present
  package:
    name:                ntp
    state:               present

- name:                  Ensure FirewallD is present
  package:
    name:                firewalld
    state:               present

- name:                  Ensure tmux is present
  package:
    name:                tmux
    state:               present

- name:                  Ensure mlocate is present
  package:
    name:                mlocate
    state:               present

- name:                  Ensure vim-common is present
  package:
    name:                vim-common
    state:               present

- name:                  Ensure yum-utils is present
  package:
    name:                yum-utils
    state:               present

- name:                  Ensure htop is present
  package:
    name:                htop
    state:               present

- name:                  Ensure device-mapper-persistent-data is present
  package:
    name:                device-mapper-persistent-data
    state:               present

- name:                  Ensure lvm2 is present
  package:
    name:                lvm2
    state:               present

#- name:                 Ensure dnf is present
#  package:
#    name:               dnf
#    state:              present

#- name:                 Ensure dnf-plugins-core present
#  package:
#    name:               dnf-plugins-core
#    state:              present

- name:                  Ensure OpenSCAP utils is present
  package:
    name:                openscap-utils
    state:               present

- name:                  Ensure SCAP security guide is present
  package:
    name:                scap-security-guide
    state:               present

- name:                  Ensure OpenSCAP daemon is present
  package:
    name:                openscap-daemon
    state:               present

- name:                  Ensure the timezone is set to UTC
  file:
    src:                 /usr/share/zoneinfo/GMT
    dest:                /etc/localtime
    state:               link

- name:                  Ensure the NTP service is running and enabled
  service:
    name:                ntpd
    state:               started
    enabled:             True

#- name:                 Ensure SSH can pass the firewall
#  firewalld:
#    service:            ssh
#    state:              enabled
#    permanent:          True
#    immediate:          True

- name:                  Ensure FirewallD is running and enabled
  service:
    name:                firewalld
    state:               started
    enabled:             True

#- name:                 Ensure the MOTD file is present and updated
#  template:
#    src:                templates/motd.jinja2
#    dest:               /etc/motd
#    owner:              root
#    group:              root
#    mode:               0644
#    become:             True

#- name:                 Set authorized key for ordinary user copying it from current user
#  authorized_key:
#  #TODO:                replace hard coded username ste with a variable
#    user:               ste
#    state:              present
#    key:                "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

#- name:                 Ensure the ordinary user is sudoer with no password required
#  lineinfile:
#    dest:               /etc/sudoers
#    state:              present
#    regexp:             '^ste ALL\='
#    line:               'ste ALL=(ALL) NOPASSWD:ALL'
#    validate:           'visudo -cf %s'

#- name:                 Ensure the hostname is the same of the inventory
#  hostname:
#    name:               "{{ inventory_hostname }}"

- name:                  Ensure kernel-ml (kernel 4.x) is present
  yum:
    name:                kernel-ml
    state:               present
    enablerepo:          elrepo-kernel
