# tasks file for base-centos7
---

# update system

- name: Ensure we have the latest version of every package
  tags:
  - skip_ansible_lint
  package:
    name: '*'
    state: latest

# configure packages repositories
- name: Ensure EPEL is present
  package:
    name: epel-release
    state: present

- name: Ensure copr repo for OpenSCAP is enabled
  yum_repository:
    name: copr-openscap
    description: OpenSCAP copr lastest
    baseurl: >-
     https://copr-be.cloud.fedoraproject.org/results/openscapmaint/openscap-latest/epel-7-$basearch/
    gpgkey: >-
     https://copr-be.cloud.fedoraproject.org/results/openscapmaint/openscap-latest/pubkey.gpg
    gpgcheck: "yes"
    repo_gpgcheck: "no"
    skip_if_unavailable: "yes"
    enabled: "yes"

- name: Ensure copr repo for cockpit-preview is enabled
  yum_repository:
    name: copr-cockpit-preview
    description: Copr repo for cockpit-preview owned by @cockpit
    baseurl: >-
     https://copr-be.cloud.fedoraproject.org/results/@cockpit/cockpit-preview/epel-7-$basearch/
    gpgkey: >-
     https://copr-be.cloud.fedoraproject.org/results/@cockpit/cockpit-preview/pubkey.gpg
    gpgcheck: "yes"
    repo_gpgcheck: "no"
    skip_if_unavailable: "yes"
    enabled: "yes"

# eventually update system with the new repositories configured

- name: Ensure we have the latest version of every package
  tags:
    - skip_ansible_lint
  package:
    name: '*'
    state: latest

# install essentials packages

- name: Ensure Python is present
  package:
    name: python
    state: present

- name: Ensure libselinux-python is present
  package:
    name: libselinux-python
    state: present

- name: Ensure selinux-policy is present
  package:
    name: selinux-policy
    state: present

- name: Ensure selinux-policy-targeted is present
  package:
    name: selinux-policy-targeted
    state: present

- name: Ensure policycoreutils-python is present
  package:
    name: policycoreutils-python
    state: present

- name: Ensure libsemanage-python is present
  package:
    name: libsemanage-python
    state: present

- name: Ensure NTP is present
  package:
    name: ntp
    state: present

- name: Ensure FirewallD is present
  package:
    name: firewalld
    state: present

- name: Ensure tmux is present
  package:
    name: tmux
    state: present

- name: Ensure vim is present
  package:
    name: vim
    state: present

- name: Ensure wget is present
  package:
    name: wget
    state: present

- name: Ensure net-tools is present
  package:
    name: net-tools
    state: present

- name: Ensure ddclient is present
  package:
    name: ddclient
    state: present

- name: Ensure perl-JSON-Any is present
  package:
    name: perl-JSON-Any
    state: present

- name: Ensure mlocate is present
  package:
    name: mlocate
    state: present

- name: Ensure vim-common is present
  package:
    name: vim-common
    state: present

- name: Ensure wget is present
  package:
    name: wget
    state: present

- name: Ensure net-tools is present
  package:
    name: net-tools
    state: present

- name: Ensure yum-utils is present
  package:
    name: yum-utils
    state: present

- name: Ensure deltarpm is present
  package:
    name: deltarpm
    state: present

- name: Ensure htop is present
  package:
    name: htop
    state: present

- name: Ensure rsync is present
  package:
    name: rsync
    state: present

- name: Ensure Performance Co-Pilot is present
  package:
    name: pcp
    state: present

- name: Ensure OpenSCAP utils is present
  package:
    name: openscap-utils
    state: present

- name: Ensure SCAP security guide is present
  package:
    name: scap-security-guide
    state: present

- name: Ensure OpenSCAP daemon is present
  package:
    name: openscap-daemon
    state: present

- name: Ensure cron(ie) is present
  package:
    name: cronie
    state: present

- name: Ensure Cockpit is present
  package:
    name: cockpit
    state: present

- name: Ensure cockpit-dashboard is present
  package:
    name: cockpit-dashboard
    state: present

- name: Ensure cockpit-storaged is present
  package:
    name: cockpit-storaged
    state: present

- name: Ensure cockpit-bridge is present
  package:
    name: cockpit-bridge
    state: present

- name: Ensure cockpit-selinux is present
  package:
    name: cockpit-selinux
    state: present

- name: Ensure redhat-lsb-core is present
  package:
    name: redhat-lsb-core
    state: present

- name: Ensure setroubleshoot-server is present
  package:
    name: setroubleshoot-server
    state: present

- name: Ensure yum-cron is present
  package:
    name: yum-cron
    state: present

- name: Ensure openssh is present
  package:
    name: openssh
    state: present

- name: Ensure openssh-server is present
  package:
    name: openssh-server
    state: present

- name: Ensure openssh-clients is present
  package:
    name: openssh-clients
    state: present

- name: Ensure openssl-libs is present
  package:
    name: openssl-libs
    state: present

- name: Ensure setroubleshoot-server is present
  package:
    name: setroubleshoot-server
    state: present

# check basic system configurations

- name: Check if running inside a docker container
  stat:
    path: /.dockerenv
  register: dockerenv_file_var

- name: Ensure SELinux is enabled
  selinux:
    policy: targeted
    state: enforcing
  when: not dockerenv_file_var.stat.exists

- name: Ensure the timezone is set to UTC
  file:
    src: /usr/share/zoneinfo/GMT
    dest: /etc/localtime
    state: link

- name: Ensure FirewallD is started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: "True"

- name: Ensure SSH can pass the firewall
  firewalld:
    service: ssh
    state: enabled
    permanent: "True"
    immediate: "True"
    zone: public

- name: Ensure Cockpit can pass the firewall
  firewalld:
    service: cockpit
    state: enabled
    permanent: "True"
    immediate: "True"
    zone: public

- name: Ensure the sshd service is started and enabled
  service:
    name: sshd
    state: started
    enabled: "True"

- name: Ensure the NTP service is started and enabled
  service:
    name: ntpd
    state: started
    enabled: "True"

- name: Ensure cron(ie) is started and enabled
  service:
    name: crond
    state: started
    enabled: "True"

- name: Ensure cockpit socket is started and enabled
  service:
    name: cockpit.socket
    state: started
    enabled: "True"

- name: Ensure Performance Co-Pilot daemon is started and enabled
  service:
    name: pmcd
    state: started
    enabled: "True"

- name: Ensure pmie is started and enabled
  service:
    name: pmie
    state: started
    enabled: "True"

- name: Ensure pmlogger is started and enabled
  service:
    name: pmlogger
    state: started
    enabled: "True"

# configure automatic security updates

- name: Configure yum-cron.conf
  template:
    src: yum-cron.conf.jinja2
    dest: /etc/yum/yum-cron.conf
  tags: yum-cron

- name: Configure yum-cron-hourly.conf
  template:
    src: yum-cron-hourly.conf.jinja2
    dest: /etc/yum/yum-cron-hourly.conf
  tags: yum-cron

- name: Ensure yum-cron service is running and enabled
  service:
    name: yum-cron
    state: started
    enabled: "yes"
  tags: yum-cron

- name: Configure yum-cron-clean to run a yum clean regularly
  template:
    src: yum-clean-cron.jinja2
    dest: /etc/cron.{{ yum_cron_clean_when }}/yum-clean-cron
    mode: 0755

- name: Ensure the MOTD file is present and updated
  template:
    src: motd.jinja2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Ensure ordinary user is present
  user:
    name: ste
    shell: /bin/bash
    groups: wheel

# configure ordinary user with ssh key login only

# set authorized key for ordinary user
- name: Set authorized key took from url
  authorized_key:
    user: ste
    state: present
    key: https://github.com/StefanoAgazzi.keys

- name: Ensure the hostname is the same of the inventory
  hostname:
    name: "{{ inventory_hostname }}"
  when: not dockerenv_file_var.stat.exists
